os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
    - tree
  homebrew:
    packages:
    - tree
    update: true

# Only clone the most recent commit.
git:
  depth: 1

language: go

go:
  - "1.12"

go_import_path: sigs.k8s.io/kustomize

before_install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then export GO111MODULE=on; else $env:GO111MODULE="on"; fi 
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then source ./travis/consider-early-travis-exit.sh; fi 
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.17.1; fi 
  - go get -u github.com/monopole/mdrip
  # The following would install Helm if needed for some reason.
  # - wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
  # - tar -xvzf helm-v2.13.1-linux-amd64.tar.gz
  # - sudo mv linux-amd64/helm /usr/local/bin/helm

# Skip the install process; let pre-commit.sh do it.
install: true

# TBD. Suppressing for now.
notifications:
  email: false

matrix:
  include:
    - os: windows
      script:
      - powershell 
      - powershell.exe ./travis/Invoke-PreCommit.ps1
    - os: linux
      script: ./travis/pre-commit.sh
    - os: linux
      script: ./travis/pre-commit.sh  
